#1 Input parameter workflow - update #23

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -52,6 +52,21 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
+      # Import PGP Private Key based on secret_category and capture fingerprint
+      - name: Import PGP Private Key and Capture Fingerprint
+        run: |
+          if [ "${{ github.event.inputs.secret_category }}" == "lending" ]; then
+            FINGERPRINT=$(echo "${{ secrets.LENDING_PGP_PRIVATE_KEY }}" | gpg --import 2>&1 | grep 'gpg: key .*:' | sed -E 's/gpg: key ([A-Z0-9]+):.*/\1/')
+          elif [ "${{ github.event.inputs.secret_category }}" == "infra" ]; then
+            FINGERPRINT=$(echo "${{ secrets.INFRA_PGP_PRIVATE_KEY }}" | gpg --import 2>&1 | grep 'gpg: key .*:' | sed -E 's/gpg: key ([A-Z0-9]+):.*/\1/')
+          elif [ "${{ github.event.inputs.secret_category }}" == "customer-experience" ]; then
+            FINGERPRINT=$(echo "${{ secrets.CE_PGP_PRIVATE_KEY }}" | gpg --import 2>&1 | grep 'gpg: key .*:' | sed -E 's/gpg: key ([A-Z0-9]+):.*/\1/')
+          else
+            echo "::error ::Invalid secret category."
+            exit 1
+          fi
+          echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV
+
       - name: Install sops
         run: |
           wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
@@ -91,6 +106,7 @@ jobs:
 
       - name: Cleanup
         run: |
+          gpg --delete-secret-keys --batch --yes ${{ env.FINGERPRINT }}
           rm -f "$SECRET_TEMP_FILE"
 
       # Additional steps to commit changes, if necessary
