#1 Input parameter workflow - update #43

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -150,24 +150,30 @@ jobs:
           wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
           sudo dpkg -i sops_3.7.1_amd64.deb
 
+      # - name: Handle Secret Value
+      #   run: |
+      #     SECRET_VALUE=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
+      #     echo "::add-mask::$SECRET_VALUE"
+      #     chmod +x scripts/wrapper.sh
+      #     SECRET_TEMP_FILE=$(./scripts/wrapper.sh)
+      #     echo "SECRET_TEMP_FILE=$SECRET_TEMP_FILE" >> $GITHUB_ENV
+
       - name: Handle Secret Value
         run: |
-          SECRET_VALUE=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
-          echo "::add-mask::$SECRET_VALUE"
-          chmod +x scripts/wrapper.sh
-          SECRET_TEMP_FILE=$(./scripts/wrapper.sh)
-          echo "SECRET_TEMP_FILE=$SECRET_TEMP_FILE" >> $GITHUB_ENV
+          INP_SECRET_VALUE=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
+          echo "::add-mask::$INP_SECRET_VALUE"
+          echo SECRET_VALUE="$INP_SECRET_VALUE" >> $GITHUB_ENV
 
-      - name: Define Secret File Path
-        run: |
-          echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
+      # - name: Define Secret File Path
+      #   run: |
+      #     echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
 
-      - name: Check if Secret File Exists
-        run: |
-          if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
-            echo "::error ::Secret file does not exist or path is incorrect."
-            exit 1
-          fi
+      # - name: Check if Secret File Exists
+      #   run: |
+      #     if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
+      #       echo "::error ::Secret file does not exist or path is incorrect."
+      #       exit 1
+      #     fi
 
       - name: Define Temporary Decrypted File Path
         run: |
@@ -178,13 +184,10 @@ jobs:
         run: |
           sops --config configs/${{ github.event.inputs.sops_version }}_sops.yaml --decrypt "${{ env.SECRET_FILE_PATH }}" > "${{ env.DECRYPTED_FILE_PATH }}"
 
-      - name: Debug - Check Temp File Content
-        run: |
-          cat "$SECRET_TEMP_FILE"
-
       - name: Update Secret File Using Temporary Secret File
         run: |
-          SECRET_VALUE=$(cat "$SECRET_TEMP_FILE")
+          SECRET_VALUE=$(cat "$SECRET_VALUE")
+          echo "Read secret value: $SECRET_VALUE" # Debugging line, remove later
           echo "${{ github.event.inputs.secret_key }}: $SECRET_VALUE" >> "${{ env.DECRYPTED_FILE_PATH }}"
 
       - name: Re-Encrypt Secret File
