#1 Input parameter workflow - update #24

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -55,17 +55,32 @@ jobs:
       # Import PGP Private Key based on secret_category and capture fingerprint
       - name: Import PGP Private Key and Capture Fingerprint
         run: |
-          if [ "${{ github.event.inputs.secret_category }}" == "lending" ]; then
-            FINGERPRINT=$(echo "${{ secrets.LENDING_PGP_PRIVATE_KEY }}" | gpg --import 2>&1 | grep 'gpg: key .*:' | sed -E 's/gpg: key ([A-Z0-9]+):.*/\1/')
-          elif [ "${{ github.event.inputs.secret_category }}" == "infra" ]; then
-            FINGERPRINT=$(echo "${{ secrets.INFRA_PGP_PRIVATE_KEY }}" | gpg --import 2>&1 | grep 'gpg: key .*:' | sed -E 's/gpg: key ([A-Z0-9]+):.*/\1/')
-          elif [ "${{ github.event.inputs.secret_category }}" == "customer-experience" ]; then
-            FINGERPRINT=$(echo "${{ secrets.CE_PGP_PRIVATE_KEY }}" | gpg --import 2>&1 | grep 'gpg: key .*:' | sed -E 's/gpg: key ([A-Z0-9]+):.*/\1/')
-          else
-            echo "::error ::Invalid secret category."
-            exit 1
-          fi
-          echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV
+          import_and_extract_fingerprint() {
+            KEY_OUTPUT=$(echo "$1" | gpg --import 2>&1)
+            echo "$KEY_OUTPUT"
+            FINGERPRINT=$(echo "$KEY_OUTPUT" | grep -oP 'key \K[A-Z0-9]{16}' | head -1)
+            if [ -z "$FINGERPRINT" ]; then
+              echo "Failed to extract fingerprint"
+              exit 1
+            fi
+            echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV
+          }
+
+          case "${{ github.event.inputs.secret_category }}" in
+            "lending")
+              import_and_extract_fingerprint "${{ secrets.LENDING_PGP_PRIVATE_KEY }}"
+              ;;
+            "infra")
+              import_and_extract_fingerprint "${{ secrets.INFRA_PGP_PRIVATE_KEY }}"
+              ;;
+            "customer-experience")
+              import_and_extract_fingerprint "${{ secrets.CE_PGP_PRIVATE_KEY }}"
+              ;;
+            *)
+              echo "::error ::Invalid secret category."
+              exit 1
+              ;;
+          esac
 
       - name: Install sops
         run: |
