#1 Input parameter workflow - update #28

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -99,6 +99,30 @@ jobs:
               ;;
           esac
 
+      - name: Export AGE Key Based on Secret Category
+        run: |
+          export_age_key() {
+            AGE_KEY="$1"
+            echo "Exporting AGE key..."
+            echo "$AGE_KEY" > age_key.txt
+          }
+
+          case "${{ github.event.inputs.secret_category }}" in
+            "lending")
+              export_age_key "${{ secrets.LENDING_AGE_KEY }}"
+              ;;
+            "infra")
+              export_age_key "${{ secrets.INFRA_AGE_KEY }}"
+              ;;
+            "customer-experience")
+              export_age_key "${{ secrets.CE_AGE_KEY }}"
+              ;;
+            *)
+              echo "::error ::Invalid secret category."
+              exit 1
+              ;;
+          esac
+
       - name: Install sops
         run: |
           wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
@@ -140,5 +164,6 @@ jobs:
         run: |
           gpg --delete-secret-keys --batch --yes ${{ env.FINGERPRINT }}
           rm -f "$SECRET_TEMP_FILE"
+          rm -f age_key.txt
 
       # Additional steps to commit changes, if necessary
