#1 Input parameter workflow - update #35

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -52,18 +52,27 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
-      # Import PGP Private Key based on secret_category and capture fingerprint
-      - name: Import PGP Private Key and Capture Fingerprint
+      # Import PGP Private and Public Key based on secret_category and capture fingerprint
+      - name: Import PGP Keys and Capture Fingerprint
         run: |
           import_and_extract_fingerprint() {
-            KEY="$1"
-            PASSPHRASE="$2"
-            echo "Importing PGP key..."
-            echo "$KEY" | gpg --batch --no-tty --import --pinentry-mode loopback --passphrase "$PASSPHRASE" 2>&1
+            PRIVATE_KEY="$1"
+            PUBLIC_KEY="$2"
+            echo "Importing PGP private key..."
+            echo "$PRIVATE_KEY" | gpg --batch --no-tty --import 2>&1
             gpg_error=$?
 
             if [ $gpg_error -ne 0 ]; then
-              echo "Failed to import PGP key, error code: $gpg_error"
+              echo "Failed to import PGP private key, error code: $gpg_error"
+              exit $gpg_error
+            fi
+
+            echo "Importing PGP public key..."
+            echo "$PUBLIC_KEY" | gpg --import 2>&1
+            gpg_error=$?
+
+            if [ $gpg_error -ne 0 ]; then
+              echo "Failed to import PGP public key, error code: $gpg_error"
               exit $gpg_error
             fi
 
@@ -85,13 +94,13 @@ jobs:
 
           case "${{ github.event.inputs.secret_category }}" in
             "lending")
-              import_and_extract_fingerprint "${{ secrets.LENDING_PGP_PRIVATE_KEY }}" "${{ secrets.LENDING_GPG_PASSPHRASE }}"
+              import_and_extract_fingerprint "${{ secrets.LENDING_PGP_PRIVATE_KEY }}" "${{ secrets.LENDING_PGP_PUBLIC_KEY }}"
               ;;
             "infra")
-              import_and_extract_fingerprint "${{ secrets.INFRA_PGP_PRIVATE_KEY }}" "${{ secrets.INFRA_GPG_PASSPHRASE }}"
+              import_and_extract_fingerprint "${{ secrets.INFRA_PGP_PRIVATE_KEY }}" "${{ secrets.INFRA_PGP_PUBLIC_KEY }}"
               ;;
             "customer-experience")
-              import_and_extract_fingerprint "${{ secrets.CE_PGP_PRIVATE_KEY }}" "${{ secrets.CE_GPG_PASSPHRASE }}"
+              import_and_extract_fingerprint "${{ secrets.CE_PGP_PRIVATE_KEY }}" "${{ secrets.CE_PGP_PUBLIC_KEY }}"
               ;;
             *)
               echo "::error ::Invalid secret category."
