#1 Input parameter workflow - update #26

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -57,11 +57,20 @@ jobs:
         run: |
           import_and_extract_fingerprint() {
             echo "Importing PGP key..."
-            KEY_OUTPUT=$(echo "$1" | gpg --import 2>&1)
-            echo "$KEY_OUTPUT"
+            echo "$1" | gpg --import 2>&1
+            gpg_error=$?
+
+            if [ $gpg_error -ne 0 ]; then
+              echo "Failed to import PGP key, error code: $gpg_error"
+              exit $gpg_error
+            fi
+
+            echo "Listing imported keys..."
+            gpg --list-keys
+            gpg --list-secret-keys
 
             echo "Extracting fingerprint..."
-            FINGERPRINT=$(echo "$KEY_OUTPUT" | grep -oP 'key \K[A-Z0-9]{16}' | head -1)
+            FINGERPRINT=$(gpg --list-secret-keys --with-colons | grep '^fpr' | head -n 1 | cut -d':' -f10)
 
             if [ -z "$FINGERPRINT" ]; then
               echo "Failed to extract fingerprint"
