#1 Input parameter workflow - update #44

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -164,16 +164,16 @@ jobs:
           echo "::add-mask::$INP_SECRET_VALUE"
           echo SECRET_VALUE="$INP_SECRET_VALUE" >> $GITHUB_ENV
 
-      # - name: Define Secret File Path
-      #   run: |
-      #     echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
+      - name: Define Secret File Path
+        run: |
+          echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
 
-      # - name: Check if Secret File Exists
-      #   run: |
-      #     if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
-      #       echo "::error ::Secret file does not exist or path is incorrect."
-      #       exit 1
-      #     fi
+      - name: Check if Secret File Exists
+        run: |
+          if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
+            echo "::error ::Secret file does not exist or path is incorrect."
+            exit 1
+          fi
 
       - name: Define Temporary Decrypted File Path
         run: |
