#1 Input parameter workflow - update #55

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -3,6 +3,13 @@ name: Create New Secret
 on:
   workflow_dispatch:
     inputs:
+      action:
+        description: 'Action to perform (create or update)'
+        required: true
+        type: choice
+        options:
+          - create
+          - update
       logLevel:
         description: 'Log level'
         required: true
@@ -164,10 +171,28 @@ jobs:
         run: |
           echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
 
-      - name: Check if Secret File Exists
+      # - name: Check if Secret File Exists
+      #   run: |
+      #     if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
+      #       echo "::error ::Secret file does not exist or path is incorrect."
+      #       exit 1
+      #     fi
+      - name: Check if Secret File Exists or Create New
         run: |
-          if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
-            echo "::error ::Secret file does not exist or path is incorrect."
+          if [ "${{ github.event.inputs.action }}" == "create" ]; then
+            echo "::notice::Creating new secret file for the new service."
+            mkdir -p "$(dirname ${{ env.SECRET_FILE_PATH }})"
+            echo "${{ github.event.inputs.secret_key }}: " > "${{ env.SECRET_FILE_PATH }}"
+            echo "isNewFile=true" >> $GITHUB_ENV
+          elif [ "${{ github.event.inputs.action }}" == "update" ]; then
+            if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
+              echo "::error::Secret file does not exist. Cannot update non-existent file."
+              exit 1
+            fi
+            echo "::notice::Updating secret for the existing service."
+            echo "isNewFile=false" >> $GITHUB_ENV
+          else
+            echo "::error::Invalid action specified."
             exit 1
           fi
 
@@ -176,8 +201,13 @@ jobs:
           DECRYPTED_FILE_PATH="$(dirname ${{ env.SECRET_FILE_PATH }})/temp_decrypted_file.yaml"
           echo "DECRYPTED_FILE_PATH=$DECRYPTED_FILE_PATH" >> $GITHUB_ENV
 
-      - name: Decrypt Secret File
+      # - name: Decrypt Secret File
+      #   run: |
+      #     sops --config configs/${{ github.event.inputs.sops_version }}_sops.yaml --decrypt "${{ env.SECRET_FILE_PATH }}" > "${{ env.DECRYPTED_FILE_PATH }}"
+      - name: Decrypt Secret File or Skip If New
+        if: env.isNewFile == 'false'
         run: |
+          echo "::notice::Decrypting existing secret file."
           sops --config configs/${{ github.event.inputs.sops_version }}_sops.yaml --decrypt "${{ env.SECRET_FILE_PATH }}" > "${{ env.DECRYPTED_FILE_PATH }}"
 
       - name: Update Secret File Based on Secret Type
