#1 Input parameter workflow - update #58

diff --git a/.github/workflows/create-new-secret.yaml b/.github/workflows/create-new-secret.yaml
--- a/.github/workflows/create-new-secret.yaml
+++ b/.github/workflows/create-new-secret.yaml
@@ -171,15 +171,32 @@ jobs:
         run: |
           echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
 
-      # - name: Check if Secret File Exists
+      # - name: Check if Secret File Exists or Create New
       #   run: |
-      #     if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
-      #       echo "::error ::Secret file does not exist or path is incorrect."
+      #     if [ "${{ github.event.inputs.action }}" == "create" ]; then
+      #       echo "::notice::Creating new secret file for the new service."
+      #       mkdir -p "$(dirname ${{ env.SECRET_FILE_PATH }})"
+      #       echo "${{ github.event.inputs.secret_key }}: " > "${{ env.SECRET_FILE_PATH }}"
+      #       echo "isNewFile=true" >> $GITHUB_ENV
+      #     elif [ "${{ github.event.inputs.action }}" == "update" ]; then
+      #       if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
+      #         echo "::error::Secret file does not exist. Cannot update non-existent file."
+      #         exit 1
+      #       fi
+      #       echo "::notice::Updating secret for the existing service."
+      #       echo "isNewFile=false" >> $GITHUB_ENV
+      #     else
+      #       echo "::error::Invalid action specified."
       #       exit 1
       #     fi
+
       - name: Check if Secret File Exists or Create New
         run: |
           if [ "${{ github.event.inputs.action }}" == "create" ]; then
+            if [ -f "${{ env.SECRET_FILE_PATH }}" ]; then
+              echo "::error::Secret file already exists for the service. Cannot create a new one."
+              exit 1
+            fi
             echo "::notice::Creating new secret file for the new service."
             mkdir -p "$(dirname ${{ env.SECRET_FILE_PATH }})"
             echo "${{ github.event.inputs.secret_key }}: " > "${{ env.SECRET_FILE_PATH }}"
