Update self-service workflow logic #1

diff --git a/.github/workflows/secret-management-workflow.yaml b/.github/workflows/secret-management-workflow.yaml
--- a/.github/workflows/secret-management-workflow.yaml
+++ b/.github/workflows/secret-management-workflow.yaml
@@ -183,6 +183,40 @@ jobs:
         run: |
           echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
 
+      - name: Check if Secret File Exists or Create New
+        run: |
+          if [ "${{ github.event.inputs.action }}" == "create" ]; then
+            if [ -f "${{ env.SECRET_FILE_PATH }}" ]; then
+              echo "::error::Secret file already exists for the service. Cannot create a new one."
+              exit 1
+            fi
+            echo "::notice::Creating new secret file for the new service."
+            mkdir -p "$(dirname ${{ env.SECRET_FILE_PATH }})"
+            echo "${{ github.event.inputs.secret_key }}: " > "${{ env.SECRET_FILE_PATH }}"
+            echo "isNewFile=true" >> $GITHUB_ENV
+          elif [ "${{ github.event.inputs.action }}" == "update" ]; then
+            if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
+              echo "::error::Secret file does not exist. Cannot update non-existent file."
+              exit 1
+            fi
+            echo "::notice::Updating secret for the existing service."
+            echo "isNewFile=false" >> $GITHUB_ENV
+          else
+            echo "::error::Invalid action specified."
+            exit 1
+          fi
+
+      - name: Define Temporary Decrypted File Path
+        run: |
+          DECRYPTED_FILE_PATH="$(dirname ${{ env.SECRET_FILE_PATH }})/temp_decrypted_file.yaml"
+          echo "DECRYPTED_FILE_PATH=$DECRYPTED_FILE_PATH" >> $GITHUB_ENV
+
+      - name: Decrypt Secret File or Skip If New
+        if: env.isNewFile == 'false'
+        run: |
+          echo "::notice::Decrypting existing secret file."
+          sops --config configs/v1_sops.yaml --decrypt "${{ env.SECRET_FILE_PATH }}" > "${{ env.DECRYPTED_FILE_PATH }}"
+
       - name: Update Secret File Based on Secret Type
         run: |
           KEY="${{ github.event.inputs.secret_key }}"
@@ -217,52 +251,17 @@ jobs:
             fi
           fi
 
-      #TODO cleanup
-      # - name: Check if Secret File Exists or Create New
+      # - name: Update Secret File Based on Secret Type
       #   run: |
-      #     if [ "${{ github.event.inputs.action }}" == "create" ]; then
-      #       if [ -f "${{ env.SECRET_FILE_PATH }}" ]; then
-      #         echo "::error::Secret file already exists for the service. Cannot create a new one."
-      #         exit 1
-      #       fi
-      #       echo "::notice::Creating new secret file for the new service."
-      #       mkdir -p "$(dirname ${{ env.SECRET_FILE_PATH }})"
-      #       echo "${{ github.event.inputs.secret_key }}: " > "${{ env.SECRET_FILE_PATH }}"
-      #       echo "isNewFile=true" >> $GITHUB_ENV
-      #     elif [ "${{ github.event.inputs.action }}" == "update" ]; then
-      #       if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
-      #         echo "::error::Secret file does not exist. Cannot update non-existent file."
-      #         exit 1
-      #       fi
-      #       echo "::notice::Updating secret for the existing service."
-      #       echo "isNewFile=false" >> $GITHUB_ENV
+      #     if [ "${{ github.event.inputs.secret_type }}" == "cert" ]; then
+      #       # Decode base64 for certificate and append as a multi-line string with indentation
+      #       echo "${{ github.event.inputs.secret_key }}: |" >> "${{ env.DECRYPTED_FILE_PATH }}"
+      #       echo "${{ env.SECRET_VALUE }}" | base64 --decode | sed 's/^/    /' >> "${{ env.DECRYPTED_FILE_PATH }}"
       #     else
-      #       echo "::error::Invalid action specified."
-      #       exit 1
+      #       # Handle as a regular single-line secret
+      #       SECRET_VALUE="${{ env.SECRET_VALUE }}"
+      #       echo "${{ github.event.inputs.secret_key }}: $SECRET_VALUE" >> "${{ env.DECRYPTED_FILE_PATH }}"
       #     fi
-
-      - name: Define Temporary Decrypted File Path
-        run: |
-          DECRYPTED_FILE_PATH="$(dirname ${{ env.SECRET_FILE_PATH }})/temp_decrypted_file.yaml"
-          echo "DECRYPTED_FILE_PATH=$DECRYPTED_FILE_PATH" >> $GITHUB_ENV
-
-      - name: Decrypt Secret File or Skip If New
-        if: env.isNewFile == 'false'
-        run: |
-          echo "::notice::Decrypting existing secret file."
-          sops --config configs/v1_sops.yaml --decrypt "${{ env.SECRET_FILE_PATH }}" > "${{ env.DECRYPTED_FILE_PATH }}"
-
-      - name: Update Secret File Based on Secret Type
-        run: |
-          if [ "${{ github.event.inputs.secret_type }}" == "cert" ]; then
-            # Decode base64 for certificate and append as a multi-line string with indentation
-            echo "${{ github.event.inputs.secret_key }}: |" >> "${{ env.DECRYPTED_FILE_PATH }}"
-            echo "${{ env.SECRET_VALUE }}" | base64 --decode | sed 's/^/    /' >> "${{ env.DECRYPTED_FILE_PATH }}"
-          else
-            # Handle as a regular single-line secret
-            SECRET_VALUE="${{ env.SECRET_VALUE }}"
-            echo "${{ github.event.inputs.secret_key }}: $SECRET_VALUE" >> "${{ env.DECRYPTED_FILE_PATH }}"
-          fi
 
       - name: Re-Encrypt Secret File
         run: |
