Updated secret publishing workflow to performs a merge of the latest updates in main branch

diff --git a/.github/workflows/secret-publishing-workflow.yaml b/.github/workflows/secret-publishing-workflow.yaml
--- a/.github/workflows/secret-publishing-workflow.yaml
+++ b/.github/workflows/secret-publishing-workflow.yaml
@@ -347,11 +347,14 @@ jobs:
             else
               git commit -m "Updated keys in modified secret files"
 
+              # Set the pull strategy to 'merge' for this operation
+              git config pull.rebase false
+
               # Pull the latest changes from the remote branch
-              git pull origin main
+              git pull origin main || (echo "Failed to pull changes from origin main" && exit 1)
 
               # Use SSH for pushing
-              git push git@github.com:meetearnest/infra-secrets.git HEAD:main
+              git push git@github.com:meetearnest/infra-secrets.git HEAD:main || (echo "Failed to push changes to origin main" && exit 1)
             fi
           else
             echo "No files to commit."
