Update self-service workflow logic

diff --git a/.github/workflows/secret-management-workflow.yaml b/.github/workflows/secret-management-workflow.yaml
--- a/.github/workflows/secret-management-workflow.yaml
+++ b/.github/workflows/secret-management-workflow.yaml
@@ -183,28 +183,63 @@ jobs:
         run: |
           echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV
 
-      - name: Check if Secret File Exists or Create New
+      - name: Update Secret File Based on Secret Type
         run: |
-          if [ "${{ github.event.inputs.action }}" == "create" ]; then
-            if [ -f "${{ env.SECRET_FILE_PATH }}" ]; then
-              echo "::error::Secret file already exists for the service. Cannot create a new one."
-              exit 1
+          KEY="${{ github.event.inputs.secret_key }}"
+          SECRET_TYPE="${{ github.event.inputs.secret_type }}"
+          ACTION="${{ github.event.inputs.action }}"
+          DECRYPTED_FILE_PATH="${{ env.DECRYPTED_FILE_PATH }}"
+          SECRET_VALUE="${{ env.SECRET_VALUE }}"
+
+          # Check if the key already exists in the file
+          if grep -q "^$KEY:" "$DECRYPTED_FILE_PATH"; then
+            if [ "$ACTION" == "update" ]; then
+              echo "Key $KEY exists. Updating its value."
+              if [ "$SECRET_TYPE" == "cert" ]; then
+                # Replace the existing key-value with the new value
+                sed -i "/^$KEY:/,/^\S/!d; /^$KEY:/a $(echo "$SECRET_VALUE" | base64 --decode | sed 's/^/    /')" "$DECRYPTED_FILE_PATH"
+              else
+                # Replace the existing single-line secret
+                sed -i "s/^$KEY:.*/$KEY: $SECRET_VALUE/" "$DECRYPTED_FILE_PATH"
+              fi
+            else
+              echo "Key $KEY already exists and action is not update. Skipping."
             fi
-            echo "::notice::Creating new secret file for the new service."
-            mkdir -p "$(dirname ${{ env.SECRET_FILE_PATH }})"
-            echo "${{ github.event.inputs.secret_key }}: " > "${{ env.SECRET_FILE_PATH }}"
-            echo "isNewFile=true" >> $GITHUB_ENV
-          elif [ "${{ github.event.inputs.action }}" == "update" ]; then
-            if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
-              echo "::error::Secret file does not exist. Cannot update non-existent file."
-              exit 1
-            fi
-            echo "::notice::Updating secret for the existing service."
-            echo "isNewFile=false" >> $GITHUB_ENV
           else
-            echo "::error::Invalid action specified."
-            exit 1
+            echo "Key $KEY does not exist. Adding it to the file."
+            if [ "$SECRET_TYPE" == "cert" ]; then
+              # Append the new key-value pair as a multi-line string with indentation
+              echo "$KEY: |" >> "$DECRYPTED_FILE_PATH"
+              echo "$SECRET_VALUE" | base64 --decode | sed 's/^/    /' >> "$DECRYPTED_FILE_PATH"
+            else
+              # Append the new single-line secret
+              echo "$KEY: $SECRET_VALUE" >> "$DECRYPTED_FILE_PATH"
+            fi
           fi
+
+      #TODO cleanup
+      # - name: Check if Secret File Exists or Create New
+      #   run: |
+      #     if [ "${{ github.event.inputs.action }}" == "create" ]; then
+      #       if [ -f "${{ env.SECRET_FILE_PATH }}" ]; then
+      #         echo "::error::Secret file already exists for the service. Cannot create a new one."
+      #         exit 1
+      #       fi
+      #       echo "::notice::Creating new secret file for the new service."
+      #       mkdir -p "$(dirname ${{ env.SECRET_FILE_PATH }})"
+      #       echo "${{ github.event.inputs.secret_key }}: " > "${{ env.SECRET_FILE_PATH }}"
+      #       echo "isNewFile=true" >> $GITHUB_ENV
+      #     elif [ "${{ github.event.inputs.action }}" == "update" ]; then
+      #       if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
+      #         echo "::error::Secret file does not exist. Cannot update non-existent file."
+      #         exit 1
+      #       fi
+      #       echo "::notice::Updating secret for the existing service."
+      #       echo "isNewFile=false" >> $GITHUB_ENV
+      #     else
+      #       echo "::error::Invalid action specified."
+      #       exit 1
+      #     fi
 
       - name: Define Temporary Decrypted File Path
         run: |
