#4 Inject secret with and without subpath for v1 and v2 secrets

diff --git a/.github/workflows/sops-secrets-publish-workflow.yaml b/.github/workflows/sops-secrets-publish-workflow.yaml
--- a/.github/workflows/sops-secrets-publish-workflow.yaml
+++ b/.github/workflows/sops-secrets-publish-workflow.yaml
@@ -26,21 +26,13 @@ jobs:
     # if: github.event_name == 'pull_request'
     needs: [pre_job]
     name: Scanning secrets via Gitleaks
-    runs-on: self-hosted #ubuntu-latest -> https://github.com/gitleaks/gitleaks-action/issues/125
+    runs-on: ubuntu-latest #self-hosted -> https://github.com/gitleaks/gitleaks-action/issues/125
     environment:
       name: system
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: Setup Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: '3.x'
-      - name: Install dependency tools
-        run: |
-          python -m pip install --upgrade pip
-          sudo apt update && sudo apt install wget
       - uses: actions/setup-node@v4.0.0
         with:
           node-version: 18
@@ -78,7 +70,7 @@ jobs:
           level: warning
   # secrets injection for vault secret engine v1
   v1_secret_vault:
-    needs: [pre_job,reviewdog]
+    needs: [pre_job,reviewdog,gitleaks]
     name: "v1 Secret Injection via Sops"
     strategy:
       matrix:
@@ -93,6 +85,18 @@ jobs:
 
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Download status
+        uses: actions/download-artifact@v3
+        with:
+          name: status
+
+      - name: Check Gitleaks status
+        run: |
+          if [[ "$(cat status.txt)" != "success" ]]; then
+            echo "Gitleaks check failed. Exiting."
+            exit 1s
+          fi
 
       - name: Install GPG
         run: |
@@ -374,7 +378,7 @@ jobs:
           # done
   # secrets injection for vault secret engine v2
   v2_secret_vault:
-    needs: [pre_job,reviewdog]
+    needs: [pre_job,reviewdog,gitleaks]
     name: "v2 Secret Injection via Sops"
     strategy:
       matrix:
@@ -389,6 +393,18 @@ jobs:
 
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Download status
+        uses: actions/download-artifact@v3
+        with:
+          name: status
+
+      - name: Check Gitleaks status
+        run: |
+          if [[ "$(cat status.txt)" != "success" ]]; then
+            echo "Gitleaks check failed. Exiting."
+            exit 1s
+          fi
 
       - name: Install GPG
         run: |
@@ -609,7 +625,7 @@ jobs:
                 # Construct the Vault path
                 filename_without_extension="$(basename $decrypted_file_path .yaml)"
                 IFS='.' read -r secret_name sub_path <<< "$filename_without_extension"
-                vault_path="secret/data/$secret_name/$sub_path"
+                vault_path="secret-v2/data/$secret_name/$sub_path"
                 echo "Uploading to Vault at path: $vault_path"
 
                 # Upload to Vault
