This is an update for publish secret steps #43

diff --git a/.github/workflows/v2_sops-workflow.yaml b/.github/workflows/v2_sops-workflow.yaml
--- a/.github/workflows/v2_sops-workflow.yaml
+++ b/.github/workflows/v2_sops-workflow.yaml
@@ -120,36 +120,45 @@ jobs:
             if [[ $(basename "$file") =~ \..+\.yaml$ ]]; then
               decrypted_file_path="${{ env.DECRYPTED_PATH }}/$(basename $file)"
               decrypted_json_path="${{ env.DECRYPTED_PATH }}/$(basename $file .yaml).json" # Path for the JSON file
+
+              # Attempt decryption but ignore errors
               echo "Decrypting double-dot file: $file"
-              sops -d --ignore-mac --verbose $file > $decrypted_file_path
+              sops -d --verbose $file > $decrypted_file_path || echo "Decryption error, might continue if threshold is met"
 
               # Debug: Check the contents of the decrypted YAML file
               echo "Decrypted YAML content:"
               cat "$decrypted_file_path"
 
-              # Convert YAML to JSON using yq
-              pip install yq
-              yq -r . "$decrypted_file_path" > "$decrypted_json_path" || echo "yq conversion failed"
+              # Check if the file has been successfully decrypted
+              if [ -s "$decrypted_file_path" ]; then
+                echo "File decrypted successfully, continuing with further processing"
 
-              # Debug: Check if the JSON file is created and list files in the directory
-              echo "Listing files in decrypted path:"
-              ls -lah "${{ env.DECRYPTED_PATH }}/"
+                # Convert YAML to JSON using yq
+                pip install yq
+                yq -r . "$decrypted_file_path" > "$decrypted_json_path" || echo "yq conversion failed"
 
-              # Debug: Output the contents of the JSON file
-              echo "Converted JSON content:"
-              cat "$decrypted_json_path"
+                # Debug: Check if the JSON file is created and list files in the directory
+                echo "Listing files in decrypted path:"
+                ls -lah "${{ env.DECRYPTED_PATH }}/"
 
+                # Debug: Output the contents of the JSON file
+                echo "Converted JSON content:"
+                cat "$decrypted_json_path"
 
-              # Construct and upload to Vault
-              filename_without_extension="$(basename $file .yaml)"
-              IFS='.' read -r secret_name sub_path <<< "$filename_without_extension"
-              vault_path="secret/data/$secret_name/$sub_path"
-              echo "Uploading to Vault at path: $vault_path"
-              curl -H "X-Vault-Token: $VAULT_TOKEN" \
-                    -H "Content-Type: application/json" \
-                    --request POST \
-                    --data @"$decrypted_json_path" \
-                    $VAULT_ADDR/v1/$vault_path
+                # Construct and upload to Vault
+                filename_without_extension="$(basename $file .yaml)"
+                IFS='.' read -r secret_name sub_path <<< "$filename_without_extension"
+                vault_path="secret/data/$secret_name/$sub_path"
+                echo "Uploading to Vault at path: $vault_path"
+                curl -H "X-Vault-Token: $VAULT_TOKEN" \
+                      -H "Content-Type: application/json" \
+                      --request POST \
+                      --data @"$decrypted_json_path" \
+                      $VAULT_ADDR/v1/$vault_path
+              else
+                echo "Failed to decrypt file: $file"
+                # Handle the failure case as needed
+              fi
             else
               echo "Publishing secret using sops for file: $file"
               sops publish -y $file
